version: '2'

services:
  postgres:
    image: kiasaki/alpine-postgres:9.5
    container_name: postgres
    networks:
      - backend-tier
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=randomTestPassword

  nginx:
    restart: always
    image: nginx:1.10.1-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes_from:
      - django
    volumes:
      - /etc/nginx/conf.d
      - /usr/share/nginx/html
    links:
      - django:django
    networks:
      - proxy-tier
    depends_on:
      - django

  nginx-gen:
    image: jwilder/docker-gen:0.7.3
    container_name: nginx-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    links:
      - django:django
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /deploy/nginx-compose-v2.tmpl /etc/nginx/conf.d/default.conf

  django:
    build: .
    container_name: django
    image: himfoodpantry/pantrydb
    environment:
      - VIRTUAL_HOST=dm.com
      - VIRTUAL_PORT=8000
      - VIRTUAL_NETWORK=himpantrydb_proxy-tier
      - DATABASE_URL=postgres://admin:randomTestPassword@postgres:5432/admin
      - ALLOWED_HOSTS=*

    depends_on:
      - postgres
    ports:
     - "8000:80"
    networks:
      - backend-tier
      - proxy-tier

networks:
  proxy-tier:
    driver: bridge
  backend-tier:
    driver: bridge